//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zopone.AddOn.PO.SeniorContrato {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="SeniorContrato.rubi_Syncbr_zopone_integracaoContrato")]
    public interface rubi_Syncbr_zopone_integracaoContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoContrato/ContratoReque" +
            "st", ReplyAction="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoContrato/ContratoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoOut Contrato(string user, string password, int encryption, Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoContrato/ContratoReque" +
            "st", ReplyAction="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoContrato/ContratoRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoOut> ContratoAsync(string user, string password, int encryption, Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class integracaoContratoContratoIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> cadResField;
        
        private bool cadResFieldSpecified;
        
        private System.Nullable<int> codOemField;
        
        private bool codOemFieldSpecified;
        
        private string datFimField;
        
        private string datIniField;
        
        private string desConField;
        
        private System.Nullable<int> empResField;
        
        private bool empResFieldSpecified;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string numConField;
        
        private System.Nullable<int> numLocField;
        
        private bool numLocFieldSpecified;
        
        private string obsConField;
        
        private System.Nullable<int> tabOrgField;
        
        private bool tabOrgFieldSpecified;
        
        private System.Nullable<int> tclResField;
        
        private bool tclResFieldSpecified;
        
        private System.Nullable<double> valConField;
        
        private bool valConFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> cadRes {
            get {
                return this.cadResField;
            }
            set {
                this.cadResField = value;
                this.RaisePropertyChanged("cadRes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cadResSpecified {
            get {
                return this.cadResFieldSpecified;
            }
            set {
                this.cadResFieldSpecified = value;
                this.RaisePropertyChanged("cadResSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> codOem {
            get {
                return this.codOemField;
            }
            set {
                this.codOemField = value;
                this.RaisePropertyChanged("codOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codOemSpecified {
            get {
                return this.codOemFieldSpecified;
            }
            set {
                this.codOemFieldSpecified = value;
                this.RaisePropertyChanged("codOemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string datFim {
            get {
                return this.datFimField;
            }
            set {
                this.datFimField = value;
                this.RaisePropertyChanged("datFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string datIni {
            get {
                return this.datIniField;
            }
            set {
                this.datIniField = value;
                this.RaisePropertyChanged("datIni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string desCon {
            get {
                return this.desConField;
            }
            set {
                this.desConField = value;
                this.RaisePropertyChanged("desCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> empRes {
            get {
                return this.empResField;
            }
            set {
                this.empResField = value;
                this.RaisePropertyChanged("empRes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool empResSpecified {
            get {
                return this.empResFieldSpecified;
            }
            set {
                this.empResFieldSpecified = value;
                this.RaisePropertyChanged("empResSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string numCon {
            get {
                return this.numConField;
            }
            set {
                this.numConField = value;
                this.RaisePropertyChanged("numCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int> numLoc {
            get {
                return this.numLocField;
            }
            set {
                this.numLocField = value;
                this.RaisePropertyChanged("numLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numLocSpecified {
            get {
                return this.numLocFieldSpecified;
            }
            set {
                this.numLocFieldSpecified = value;
                this.RaisePropertyChanged("numLocSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string obsCon {
            get {
                return this.obsConField;
            }
            set {
                this.obsConField = value;
                this.RaisePropertyChanged("obsCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<int> tabOrg {
            get {
                return this.tabOrgField;
            }
            set {
                this.tabOrgField = value;
                this.RaisePropertyChanged("tabOrg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tabOrgSpecified {
            get {
                return this.tabOrgFieldSpecified;
            }
            set {
                this.tabOrgFieldSpecified = value;
                this.RaisePropertyChanged("tabOrgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<int> tclRes {
            get {
                return this.tclResField;
            }
            set {
                this.tclResField = value;
                this.RaisePropertyChanged("tclRes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tclResSpecified {
            get {
                return this.tclResFieldSpecified;
            }
            set {
                this.tclResFieldSpecified = value;
                this.RaisePropertyChanged("tclResSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<double> valCon {
            get {
                return this.valConField;
            }
            set {
                this.valConField = value;
                this.RaisePropertyChanged("valCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valConSpecified {
            get {
                return this.valConFieldSpecified;
            }
            set {
                this.valConFieldSpecified = value;
                this.RaisePropertyChanged("valConSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class integracaoContratoContratoOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface rubi_Syncbr_zopone_integracaoContratoChannel : Zopone.AddOn.PO.SeniorContrato.rubi_Syncbr_zopone_integracaoContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rubi_Syncbr_zopone_integracaoContratoClient : System.ServiceModel.ClientBase<Zopone.AddOn.PO.SeniorContrato.rubi_Syncbr_zopone_integracaoContrato>, Zopone.AddOn.PO.SeniorContrato.rubi_Syncbr_zopone_integracaoContrato {
        
        public rubi_Syncbr_zopone_integracaoContratoClient() {
        }
        
        public rubi_Syncbr_zopone_integracaoContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public rubi_Syncbr_zopone_integracaoContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_Syncbr_zopone_integracaoContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_Syncbr_zopone_integracaoContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoOut Contrato(string user, string password, int encryption, Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoIn parameters) {
            return base.Channel.Contrato(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoOut> ContratoAsync(string user, string password, int encryption, Zopone.AddOn.PO.SeniorContrato.integracaoContratoContratoIn parameters) {
            return base.Channel.ContratoAsync(user, password, encryption, parameters);
        }
    }
}
