//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zopone.AddOn.PO.SeniorOutraEmpresa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="SeniorOutraEmpresa.rubi_Syncbr_zopone_integracaoOutraEmpresa")]
    public interface rubi_Syncbr_zopone_integracaoOutraEmpresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoOutraEmpresa/OutraEmpr" +
            "esaRequest", ReplyAction="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoOutraEmpresa/OutraEmpr" +
            "esaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaOut OutraEmpresa(string user, string password, int encryption, Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoOutraEmpresa/OutraEmpr" +
            "esaRequest", ReplyAction="http://services.senior.com.br/rubi_Syncbr_zopone_integracaoOutraEmpresa/OutraEmpr" +
            "esaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaOut> OutraEmpresaAsync(string user, string password, int encryption, Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class integracaoOutraEmpresaOutraEmpresaIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string anaSalField;
        
        private string apeOemField;
        
        private System.Nullable<int> atiIssField;
        
        private bool atiIssFieldSpecified;
        
        private string capEmpField;
        
        private System.Nullable<int> cnaPreField;
        
        private bool cnaPreFieldSpecified;
        
        private System.Nullable<int> codAtdField;
        
        private bool codAtdFieldSpecified;
        
        private System.Nullable<int> codAtiField;
        
        private bool codAtiFieldSpecified;
        
        private System.Nullable<int> codAtuField;
        
        private bool codAtuFieldSpecified;
        
        private System.Nullable<int> codBaiField;
        
        private bool codBaiFieldSpecified;
        
        private System.Nullable<int> codCepField;
        
        private bool codCepFieldSpecified;
        
        private System.Nullable<int> codCidField;
        
        private bool codCidFieldSpecified;
        
        private System.Nullable<int> codCliField;
        
        private bool codCliFieldSpecified;
        
        private string codEstField;
        
        private System.Nullable<int> codEveField;
        
        private bool codEveFieldSpecified;
        
        private System.Nullable<int> codForField;
        
        private bool codForFieldSpecified;
        
        private System.Nullable<int> codFpaField;
        
        private bool codFpaFieldSpecified;
        
        private System.Nullable<int> codMicField;
        
        private bool codMicFieldSpecified;
        
        private System.Nullable<int> codOemField;
        
        private bool codOemFieldSpecified;
        
        private System.Nullable<int> codPaiField;
        
        private bool codPaiFieldSpecified;
        
        private System.Nullable<int> codSinField;
        
        private bool codSinFieldSpecified;
        
        private System.Nullable<int> colAdmField;
        
        private bool colAdmFieldSpecified;
        
        private System.Nullable<int> colExeField;
        
        private bool colExeFieldSpecified;
        
        private System.Nullable<int> colOpeField;
        
        private bool colOpeFieldSpecified;
        
        private string conSefField;
        
        private string datIncField;
        
        private System.Nullable<int> dddFaxField;
        
        private bool dddFaxFieldSpecified;
        
        private System.Nullable<int> dddTelField;
        
        private bool dddTelFieldSpecified;
        
        private System.Nullable<int> ddiFaxField;
        
        private bool ddiFaxFieldSpecified;
        
        private System.Nullable<int> ddiTelField;
        
        private bool ddiTelFieldSpecified;
        
        private string emaEmpField;
        
        private System.Nullable<int> empCraField;
        
        private bool empCraFieldSpecified;
        
        private System.Nullable<int> empProField;
        
        private bool empProFieldSpecified;
        
        private string empPubField;
        
        private string endCplField;
        
        private string endNumField;
        
        private string endOemField;
        
        private System.Nullable<int> estCarField;
        
        private bool estCarFieldSpecified;
        
        private string faxRamField;
        
        private string fimValField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<double> folAdmField;
        
        private bool folAdmFieldSpecified;
        
        private System.Nullable<double> folExeField;
        
        private bool folExeFieldSpecified;
        
        private System.Nullable<double> folOpeField;
        
        private bool folOpeFieldSpecified;
        
        private string homPagField;
        
        private System.Nullable<int> horIncField;
        
        private bool horIncFieldSpecified;
        
        private System.Nullable<int> indObrField;
        
        private bool indObrFieldSpecified;
        
        private string iniValField;
        
        private System.Nullable<int> insConField;
        
        private bool insConFieldSpecified;
        
        private string insEstField;
        
        private System.Nullable<int> insProField;
        
        private bool insProFieldSpecified;
        
        private string intBDCField;
        
        private System.Nullable<int> nCAEPFField;
        
        private bool nCAEPFFieldSpecified;
        
        private string nomOemField;
        
        private System.Nullable<int> numCNOField;
        
        private bool numCNOFieldSpecified;
        
        private System.Nullable<int> numCerField;
        
        private bool numCerFieldSpecified;
        
        private System.Nullable<int> numCgcField;
        
        private bool numCgcFieldSpecified;
        
        private string numFaxField;
        
        private string numRamField;
        
        private string numTelField;
        
        private string obsOemField;
        
        private System.Nullable<double> perCofField;
        
        private bool perCofFieldSpecified;
        
        private System.Nullable<double> perCslField;
        
        private bool perCslFieldSpecified;
        
        private System.Nullable<double> perCsrField;
        
        private bool perCsrFieldSpecified;
        
        private System.Nullable<double> perGcoField;
        
        private bool perGcoFieldSpecified;
        
        private System.Nullable<double> perInsField;
        
        private bool perInsFieldSpecified;
        
        private System.Nullable<double> perIrfField;
        
        private bool perIrfFieldSpecified;
        
        private System.Nullable<double> perIssField;
        
        private bool perIssFieldSpecified;
        
        private System.Nullable<double> perPisField;
        
        private bool perPisFieldSpecified;
        
        private System.Nullable<double> perRetField;
        
        private bool perRetFieldSpecified;
        
        private string pesCo1Field;
        
        private string pesCo2Field;
        
        private System.Nullable<int> qtdCanField;
        
        private bool qtdCanFieldSpecified;
        
        private System.Nullable<int> regAnsField;
        
        private bool regAnsFieldSpecified;
        
        private System.Nullable<int> regCodField;
        
        private bool regCodFieldSpecified;
        
        private System.Nullable<int> retCofField;
        
        private bool retCofFieldSpecified;
        
        private System.Nullable<int> retCslField;
        
        private bool retCslFieldSpecified;
        
        private System.Nullable<int> retCsrField;
        
        private bool retCsrFieldSpecified;
        
        private System.Nullable<int> retIrfField;
        
        private bool retIrfFieldSpecified;
        
        private System.Nullable<int> retPisField;
        
        private bool retPisFieldSpecified;
        
        private string sinEmpField;
        
        private System.Nullable<int> staBDCField;
        
        private bool staBDCFieldSpecified;
        
        private System.Nullable<int> tInConField;
        
        private bool tInConFieldSpecified;
        
        private System.Nullable<int> tInProField;
        
        private bool tInProFieldSpecified;
        
        private System.Nullable<int> tabEveField;
        
        private bool tabEveFieldSpecified;
        
        private System.Nullable<int> tipFatField;
        
        private bool tipFatFieldSpecified;
        
        private System.Nullable<int> tipInsField;
        
        private bool tipInsFieldSpecified;
        
        private string tipLgrField;
        
        private System.Nullable<int> tipUsoField;
        
        private bool tipUsoFieldSpecified;
        
        private System.Nullable<int> ultPesField;
        
        private bool ultPesFieldSpecified;
        
        private System.Nullable<int> viaCraField;
        
        private bool viaCraFieldSpecified;
        
        private System.Nullable<int> viaProField;
        
        private bool viaProFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string anaSal {
            get {
                return this.anaSalField;
            }
            set {
                this.anaSalField = value;
                this.RaisePropertyChanged("anaSal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string apeOem {
            get {
                return this.apeOemField;
            }
            set {
                this.apeOemField = value;
                this.RaisePropertyChanged("apeOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> atiIss {
            get {
                return this.atiIssField;
            }
            set {
                this.atiIssField = value;
                this.RaisePropertyChanged("atiIss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atiIssSpecified {
            get {
                return this.atiIssFieldSpecified;
            }
            set {
                this.atiIssFieldSpecified = value;
                this.RaisePropertyChanged("atiIssSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string capEmp {
            get {
                return this.capEmpField;
            }
            set {
                this.capEmpField = value;
                this.RaisePropertyChanged("capEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> cnaPre {
            get {
                return this.cnaPreField;
            }
            set {
                this.cnaPreField = value;
                this.RaisePropertyChanged("cnaPre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cnaPreSpecified {
            get {
                return this.cnaPreFieldSpecified;
            }
            set {
                this.cnaPreFieldSpecified = value;
                this.RaisePropertyChanged("cnaPreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> codAtd {
            get {
                return this.codAtdField;
            }
            set {
                this.codAtdField = value;
                this.RaisePropertyChanged("codAtd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codAtdSpecified {
            get {
                return this.codAtdFieldSpecified;
            }
            set {
                this.codAtdFieldSpecified = value;
                this.RaisePropertyChanged("codAtdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<int> codAti {
            get {
                return this.codAtiField;
            }
            set {
                this.codAtiField = value;
                this.RaisePropertyChanged("codAti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codAtiSpecified {
            get {
                return this.codAtiFieldSpecified;
            }
            set {
                this.codAtiFieldSpecified = value;
                this.RaisePropertyChanged("codAtiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<int> codAtu {
            get {
                return this.codAtuField;
            }
            set {
                this.codAtuField = value;
                this.RaisePropertyChanged("codAtu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codAtuSpecified {
            get {
                return this.codAtuFieldSpecified;
            }
            set {
                this.codAtuFieldSpecified = value;
                this.RaisePropertyChanged("codAtuSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> codBai {
            get {
                return this.codBaiField;
            }
            set {
                this.codBaiField = value;
                this.RaisePropertyChanged("codBai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codBaiSpecified {
            get {
                return this.codBaiFieldSpecified;
            }
            set {
                this.codBaiFieldSpecified = value;
                this.RaisePropertyChanged("codBaiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int> codCep {
            get {
                return this.codCepField;
            }
            set {
                this.codCepField = value;
                this.RaisePropertyChanged("codCep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codCepSpecified {
            get {
                return this.codCepFieldSpecified;
            }
            set {
                this.codCepFieldSpecified = value;
                this.RaisePropertyChanged("codCepSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<int> codCid {
            get {
                return this.codCidField;
            }
            set {
                this.codCidField = value;
                this.RaisePropertyChanged("codCid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codCidSpecified {
            get {
                return this.codCidFieldSpecified;
            }
            set {
                this.codCidFieldSpecified = value;
                this.RaisePropertyChanged("codCidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<int> codCli {
            get {
                return this.codCliField;
            }
            set {
                this.codCliField = value;
                this.RaisePropertyChanged("codCli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codCliSpecified {
            get {
                return this.codCliFieldSpecified;
            }
            set {
                this.codCliFieldSpecified = value;
                this.RaisePropertyChanged("codCliSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string codEst {
            get {
                return this.codEstField;
            }
            set {
                this.codEstField = value;
                this.RaisePropertyChanged("codEst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<int> codEve {
            get {
                return this.codEveField;
            }
            set {
                this.codEveField = value;
                this.RaisePropertyChanged("codEve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codEveSpecified {
            get {
                return this.codEveFieldSpecified;
            }
            set {
                this.codEveFieldSpecified = value;
                this.RaisePropertyChanged("codEveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public System.Nullable<int> codFor {
            get {
                return this.codForField;
            }
            set {
                this.codForField = value;
                this.RaisePropertyChanged("codFor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codForSpecified {
            get {
                return this.codForFieldSpecified;
            }
            set {
                this.codForFieldSpecified = value;
                this.RaisePropertyChanged("codForSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public System.Nullable<int> codFpa {
            get {
                return this.codFpaField;
            }
            set {
                this.codFpaField = value;
                this.RaisePropertyChanged("codFpa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFpaSpecified {
            get {
                return this.codFpaFieldSpecified;
            }
            set {
                this.codFpaFieldSpecified = value;
                this.RaisePropertyChanged("codFpaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public System.Nullable<int> codMic {
            get {
                return this.codMicField;
            }
            set {
                this.codMicField = value;
                this.RaisePropertyChanged("codMic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codMicSpecified {
            get {
                return this.codMicFieldSpecified;
            }
            set {
                this.codMicFieldSpecified = value;
                this.RaisePropertyChanged("codMicSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public System.Nullable<int> codOem {
            get {
                return this.codOemField;
            }
            set {
                this.codOemField = value;
                this.RaisePropertyChanged("codOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codOemSpecified {
            get {
                return this.codOemFieldSpecified;
            }
            set {
                this.codOemFieldSpecified = value;
                this.RaisePropertyChanged("codOemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public System.Nullable<int> codPai {
            get {
                return this.codPaiField;
            }
            set {
                this.codPaiField = value;
                this.RaisePropertyChanged("codPai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codPaiSpecified {
            get {
                return this.codPaiFieldSpecified;
            }
            set {
                this.codPaiFieldSpecified = value;
                this.RaisePropertyChanged("codPaiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public System.Nullable<int> codSin {
            get {
                return this.codSinField;
            }
            set {
                this.codSinField = value;
                this.RaisePropertyChanged("codSin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codSinSpecified {
            get {
                return this.codSinFieldSpecified;
            }
            set {
                this.codSinFieldSpecified = value;
                this.RaisePropertyChanged("codSinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public System.Nullable<int> colAdm {
            get {
                return this.colAdmField;
            }
            set {
                this.colAdmField = value;
                this.RaisePropertyChanged("colAdm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool colAdmSpecified {
            get {
                return this.colAdmFieldSpecified;
            }
            set {
                this.colAdmFieldSpecified = value;
                this.RaisePropertyChanged("colAdmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public System.Nullable<int> colExe {
            get {
                return this.colExeField;
            }
            set {
                this.colExeField = value;
                this.RaisePropertyChanged("colExe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool colExeSpecified {
            get {
                return this.colExeFieldSpecified;
            }
            set {
                this.colExeFieldSpecified = value;
                this.RaisePropertyChanged("colExeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public System.Nullable<int> colOpe {
            get {
                return this.colOpeField;
            }
            set {
                this.colOpeField = value;
                this.RaisePropertyChanged("colOpe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool colOpeSpecified {
            get {
                return this.colOpeFieldSpecified;
            }
            set {
                this.colOpeFieldSpecified = value;
                this.RaisePropertyChanged("colOpeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string conSef {
            get {
                return this.conSefField;
            }
            set {
                this.conSefField = value;
                this.RaisePropertyChanged("conSef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public string datInc {
            get {
                return this.datIncField;
            }
            set {
                this.datIncField = value;
                this.RaisePropertyChanged("datInc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public System.Nullable<int> dddFax {
            get {
                return this.dddFaxField;
            }
            set {
                this.dddFaxField = value;
                this.RaisePropertyChanged("dddFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dddFaxSpecified {
            get {
                return this.dddFaxFieldSpecified;
            }
            set {
                this.dddFaxFieldSpecified = value;
                this.RaisePropertyChanged("dddFaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public System.Nullable<int> dddTel {
            get {
                return this.dddTelField;
            }
            set {
                this.dddTelField = value;
                this.RaisePropertyChanged("dddTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dddTelSpecified {
            get {
                return this.dddTelFieldSpecified;
            }
            set {
                this.dddTelFieldSpecified = value;
                this.RaisePropertyChanged("dddTelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=27)]
        public System.Nullable<int> ddiFax {
            get {
                return this.ddiFaxField;
            }
            set {
                this.ddiFaxField = value;
                this.RaisePropertyChanged("ddiFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddiFaxSpecified {
            get {
                return this.ddiFaxFieldSpecified;
            }
            set {
                this.ddiFaxFieldSpecified = value;
                this.RaisePropertyChanged("ddiFaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public System.Nullable<int> ddiTel {
            get {
                return this.ddiTelField;
            }
            set {
                this.ddiTelField = value;
                this.RaisePropertyChanged("ddiTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddiTelSpecified {
            get {
                return this.ddiTelFieldSpecified;
            }
            set {
                this.ddiTelFieldSpecified = value;
                this.RaisePropertyChanged("ddiTelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public string emaEmp {
            get {
                return this.emaEmpField;
            }
            set {
                this.emaEmpField = value;
                this.RaisePropertyChanged("emaEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=30)]
        public System.Nullable<int> empCra {
            get {
                return this.empCraField;
            }
            set {
                this.empCraField = value;
                this.RaisePropertyChanged("empCra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool empCraSpecified {
            get {
                return this.empCraFieldSpecified;
            }
            set {
                this.empCraFieldSpecified = value;
                this.RaisePropertyChanged("empCraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=31)]
        public System.Nullable<int> empPro {
            get {
                return this.empProField;
            }
            set {
                this.empProField = value;
                this.RaisePropertyChanged("empPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool empProSpecified {
            get {
                return this.empProFieldSpecified;
            }
            set {
                this.empProFieldSpecified = value;
                this.RaisePropertyChanged("empProSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=32)]
        public string empPub {
            get {
                return this.empPubField;
            }
            set {
                this.empPubField = value;
                this.RaisePropertyChanged("empPub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=33)]
        public string endCpl {
            get {
                return this.endCplField;
            }
            set {
                this.endCplField = value;
                this.RaisePropertyChanged("endCpl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=34)]
        public string endNum {
            get {
                return this.endNumField;
            }
            set {
                this.endNumField = value;
                this.RaisePropertyChanged("endNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=35)]
        public string endOem {
            get {
                return this.endOemField;
            }
            set {
                this.endOemField = value;
                this.RaisePropertyChanged("endOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=36)]
        public System.Nullable<int> estCar {
            get {
                return this.estCarField;
            }
            set {
                this.estCarField = value;
                this.RaisePropertyChanged("estCar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estCarSpecified {
            get {
                return this.estCarFieldSpecified;
            }
            set {
                this.estCarFieldSpecified = value;
                this.RaisePropertyChanged("estCarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=37)]
        public string faxRam {
            get {
                return this.faxRamField;
            }
            set {
                this.faxRamField = value;
                this.RaisePropertyChanged("faxRam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=38)]
        public string fimVal {
            get {
                return this.fimValField;
            }
            set {
                this.fimValField = value;
                this.RaisePropertyChanged("fimVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=39)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=40)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=41)]
        public System.Nullable<double> folAdm {
            get {
                return this.folAdmField;
            }
            set {
                this.folAdmField = value;
                this.RaisePropertyChanged("folAdm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folAdmSpecified {
            get {
                return this.folAdmFieldSpecified;
            }
            set {
                this.folAdmFieldSpecified = value;
                this.RaisePropertyChanged("folAdmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=42)]
        public System.Nullable<double> folExe {
            get {
                return this.folExeField;
            }
            set {
                this.folExeField = value;
                this.RaisePropertyChanged("folExe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folExeSpecified {
            get {
                return this.folExeFieldSpecified;
            }
            set {
                this.folExeFieldSpecified = value;
                this.RaisePropertyChanged("folExeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=43)]
        public System.Nullable<double> folOpe {
            get {
                return this.folOpeField;
            }
            set {
                this.folOpeField = value;
                this.RaisePropertyChanged("folOpe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folOpeSpecified {
            get {
                return this.folOpeFieldSpecified;
            }
            set {
                this.folOpeFieldSpecified = value;
                this.RaisePropertyChanged("folOpeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=44)]
        public string homPag {
            get {
                return this.homPagField;
            }
            set {
                this.homPagField = value;
                this.RaisePropertyChanged("homPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=45)]
        public System.Nullable<int> horInc {
            get {
                return this.horIncField;
            }
            set {
                this.horIncField = value;
                this.RaisePropertyChanged("horInc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horIncSpecified {
            get {
                return this.horIncFieldSpecified;
            }
            set {
                this.horIncFieldSpecified = value;
                this.RaisePropertyChanged("horIncSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=46)]
        public System.Nullable<int> indObr {
            get {
                return this.indObrField;
            }
            set {
                this.indObrField = value;
                this.RaisePropertyChanged("indObr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indObrSpecified {
            get {
                return this.indObrFieldSpecified;
            }
            set {
                this.indObrFieldSpecified = value;
                this.RaisePropertyChanged("indObrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=47)]
        public string iniVal {
            get {
                return this.iniValField;
            }
            set {
                this.iniValField = value;
                this.RaisePropertyChanged("iniVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=48)]
        public System.Nullable<int> insCon {
            get {
                return this.insConField;
            }
            set {
                this.insConField = value;
                this.RaisePropertyChanged("insCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool insConSpecified {
            get {
                return this.insConFieldSpecified;
            }
            set {
                this.insConFieldSpecified = value;
                this.RaisePropertyChanged("insConSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=49)]
        public string insEst {
            get {
                return this.insEstField;
            }
            set {
                this.insEstField = value;
                this.RaisePropertyChanged("insEst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=50)]
        public System.Nullable<int> insPro {
            get {
                return this.insProField;
            }
            set {
                this.insProField = value;
                this.RaisePropertyChanged("insPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool insProSpecified {
            get {
                return this.insProFieldSpecified;
            }
            set {
                this.insProFieldSpecified = value;
                this.RaisePropertyChanged("insProSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=51)]
        public string intBDC {
            get {
                return this.intBDCField;
            }
            set {
                this.intBDCField = value;
                this.RaisePropertyChanged("intBDC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=52)]
        public System.Nullable<int> NCAEPF {
            get {
                return this.nCAEPFField;
            }
            set {
                this.nCAEPFField = value;
                this.RaisePropertyChanged("NCAEPF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NCAEPFSpecified {
            get {
                return this.nCAEPFFieldSpecified;
            }
            set {
                this.nCAEPFFieldSpecified = value;
                this.RaisePropertyChanged("NCAEPFSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=53)]
        public string nomOem {
            get {
                return this.nomOemField;
            }
            set {
                this.nomOemField = value;
                this.RaisePropertyChanged("nomOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=54)]
        public System.Nullable<int> numCNO {
            get {
                return this.numCNOField;
            }
            set {
                this.numCNOField = value;
                this.RaisePropertyChanged("numCNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCNOSpecified {
            get {
                return this.numCNOFieldSpecified;
            }
            set {
                this.numCNOFieldSpecified = value;
                this.RaisePropertyChanged("numCNOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=55)]
        public System.Nullable<int> numCer {
            get {
                return this.numCerField;
            }
            set {
                this.numCerField = value;
                this.RaisePropertyChanged("numCer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCerSpecified {
            get {
                return this.numCerFieldSpecified;
            }
            set {
                this.numCerFieldSpecified = value;
                this.RaisePropertyChanged("numCerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=56)]
        public System.Nullable<int> numCgc {
            get {
                return this.numCgcField;
            }
            set {
                this.numCgcField = value;
                this.RaisePropertyChanged("numCgc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCgcSpecified {
            get {
                return this.numCgcFieldSpecified;
            }
            set {
                this.numCgcFieldSpecified = value;
                this.RaisePropertyChanged("numCgcSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=57)]
        public string numFax {
            get {
                return this.numFaxField;
            }
            set {
                this.numFaxField = value;
                this.RaisePropertyChanged("numFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=58)]
        public string numRam {
            get {
                return this.numRamField;
            }
            set {
                this.numRamField = value;
                this.RaisePropertyChanged("numRam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=59)]
        public string numTel {
            get {
                return this.numTelField;
            }
            set {
                this.numTelField = value;
                this.RaisePropertyChanged("numTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=60)]
        public string obsOem {
            get {
                return this.obsOemField;
            }
            set {
                this.obsOemField = value;
                this.RaisePropertyChanged("obsOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=61)]
        public System.Nullable<double> perCof {
            get {
                return this.perCofField;
            }
            set {
                this.perCofField = value;
                this.RaisePropertyChanged("perCof");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perCofSpecified {
            get {
                return this.perCofFieldSpecified;
            }
            set {
                this.perCofFieldSpecified = value;
                this.RaisePropertyChanged("perCofSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=62)]
        public System.Nullable<double> perCsl {
            get {
                return this.perCslField;
            }
            set {
                this.perCslField = value;
                this.RaisePropertyChanged("perCsl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perCslSpecified {
            get {
                return this.perCslFieldSpecified;
            }
            set {
                this.perCslFieldSpecified = value;
                this.RaisePropertyChanged("perCslSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=63)]
        public System.Nullable<double> perCsr {
            get {
                return this.perCsrField;
            }
            set {
                this.perCsrField = value;
                this.RaisePropertyChanged("perCsr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perCsrSpecified {
            get {
                return this.perCsrFieldSpecified;
            }
            set {
                this.perCsrFieldSpecified = value;
                this.RaisePropertyChanged("perCsrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=64)]
        public System.Nullable<double> perGco {
            get {
                return this.perGcoField;
            }
            set {
                this.perGcoField = value;
                this.RaisePropertyChanged("perGco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perGcoSpecified {
            get {
                return this.perGcoFieldSpecified;
            }
            set {
                this.perGcoFieldSpecified = value;
                this.RaisePropertyChanged("perGcoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=65)]
        public System.Nullable<double> perIns {
            get {
                return this.perInsField;
            }
            set {
                this.perInsField = value;
                this.RaisePropertyChanged("perIns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perInsSpecified {
            get {
                return this.perInsFieldSpecified;
            }
            set {
                this.perInsFieldSpecified = value;
                this.RaisePropertyChanged("perInsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=66)]
        public System.Nullable<double> perIrf {
            get {
                return this.perIrfField;
            }
            set {
                this.perIrfField = value;
                this.RaisePropertyChanged("perIrf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perIrfSpecified {
            get {
                return this.perIrfFieldSpecified;
            }
            set {
                this.perIrfFieldSpecified = value;
                this.RaisePropertyChanged("perIrfSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=67)]
        public System.Nullable<double> perIss {
            get {
                return this.perIssField;
            }
            set {
                this.perIssField = value;
                this.RaisePropertyChanged("perIss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perIssSpecified {
            get {
                return this.perIssFieldSpecified;
            }
            set {
                this.perIssFieldSpecified = value;
                this.RaisePropertyChanged("perIssSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=68)]
        public System.Nullable<double> perPis {
            get {
                return this.perPisField;
            }
            set {
                this.perPisField = value;
                this.RaisePropertyChanged("perPis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perPisSpecified {
            get {
                return this.perPisFieldSpecified;
            }
            set {
                this.perPisFieldSpecified = value;
                this.RaisePropertyChanged("perPisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=69)]
        public System.Nullable<double> perRet {
            get {
                return this.perRetField;
            }
            set {
                this.perRetField = value;
                this.RaisePropertyChanged("perRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perRetSpecified {
            get {
                return this.perRetFieldSpecified;
            }
            set {
                this.perRetFieldSpecified = value;
                this.RaisePropertyChanged("perRetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=70)]
        public string pesCo1 {
            get {
                return this.pesCo1Field;
            }
            set {
                this.pesCo1Field = value;
                this.RaisePropertyChanged("pesCo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=71)]
        public string pesCo2 {
            get {
                return this.pesCo2Field;
            }
            set {
                this.pesCo2Field = value;
                this.RaisePropertyChanged("pesCo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=72)]
        public System.Nullable<int> qtdCan {
            get {
                return this.qtdCanField;
            }
            set {
                this.qtdCanField = value;
                this.RaisePropertyChanged("qtdCan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qtdCanSpecified {
            get {
                return this.qtdCanFieldSpecified;
            }
            set {
                this.qtdCanFieldSpecified = value;
                this.RaisePropertyChanged("qtdCanSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=73)]
        public System.Nullable<int> regAns {
            get {
                return this.regAnsField;
            }
            set {
                this.regAnsField = value;
                this.RaisePropertyChanged("regAns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regAnsSpecified {
            get {
                return this.regAnsFieldSpecified;
            }
            set {
                this.regAnsFieldSpecified = value;
                this.RaisePropertyChanged("regAnsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=74)]
        public System.Nullable<int> regCod {
            get {
                return this.regCodField;
            }
            set {
                this.regCodField = value;
                this.RaisePropertyChanged("regCod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regCodSpecified {
            get {
                return this.regCodFieldSpecified;
            }
            set {
                this.regCodFieldSpecified = value;
                this.RaisePropertyChanged("regCodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=75)]
        public System.Nullable<int> retCof {
            get {
                return this.retCofField;
            }
            set {
                this.retCofField = value;
                this.RaisePropertyChanged("retCof");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retCofSpecified {
            get {
                return this.retCofFieldSpecified;
            }
            set {
                this.retCofFieldSpecified = value;
                this.RaisePropertyChanged("retCofSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=76)]
        public System.Nullable<int> retCsl {
            get {
                return this.retCslField;
            }
            set {
                this.retCslField = value;
                this.RaisePropertyChanged("retCsl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retCslSpecified {
            get {
                return this.retCslFieldSpecified;
            }
            set {
                this.retCslFieldSpecified = value;
                this.RaisePropertyChanged("retCslSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=77)]
        public System.Nullable<int> retCsr {
            get {
                return this.retCsrField;
            }
            set {
                this.retCsrField = value;
                this.RaisePropertyChanged("retCsr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retCsrSpecified {
            get {
                return this.retCsrFieldSpecified;
            }
            set {
                this.retCsrFieldSpecified = value;
                this.RaisePropertyChanged("retCsrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=78)]
        public System.Nullable<int> retIrf {
            get {
                return this.retIrfField;
            }
            set {
                this.retIrfField = value;
                this.RaisePropertyChanged("retIrf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retIrfSpecified {
            get {
                return this.retIrfFieldSpecified;
            }
            set {
                this.retIrfFieldSpecified = value;
                this.RaisePropertyChanged("retIrfSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=79)]
        public System.Nullable<int> retPis {
            get {
                return this.retPisField;
            }
            set {
                this.retPisField = value;
                this.RaisePropertyChanged("retPis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retPisSpecified {
            get {
                return this.retPisFieldSpecified;
            }
            set {
                this.retPisFieldSpecified = value;
                this.RaisePropertyChanged("retPisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=80)]
        public string sinEmp {
            get {
                return this.sinEmpField;
            }
            set {
                this.sinEmpField = value;
                this.RaisePropertyChanged("sinEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=81)]
        public System.Nullable<int> staBDC {
            get {
                return this.staBDCField;
            }
            set {
                this.staBDCField = value;
                this.RaisePropertyChanged("staBDC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool staBDCSpecified {
            get {
                return this.staBDCFieldSpecified;
            }
            set {
                this.staBDCFieldSpecified = value;
                this.RaisePropertyChanged("staBDCSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=82)]
        public System.Nullable<int> TInCon {
            get {
                return this.tInConField;
            }
            set {
                this.tInConField = value;
                this.RaisePropertyChanged("TInCon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TInConSpecified {
            get {
                return this.tInConFieldSpecified;
            }
            set {
                this.tInConFieldSpecified = value;
                this.RaisePropertyChanged("TInConSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=83)]
        public System.Nullable<int> TInPro {
            get {
                return this.tInProField;
            }
            set {
                this.tInProField = value;
                this.RaisePropertyChanged("TInPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TInProSpecified {
            get {
                return this.tInProFieldSpecified;
            }
            set {
                this.tInProFieldSpecified = value;
                this.RaisePropertyChanged("TInProSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=84)]
        public System.Nullable<int> tabEve {
            get {
                return this.tabEveField;
            }
            set {
                this.tabEveField = value;
                this.RaisePropertyChanged("tabEve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tabEveSpecified {
            get {
                return this.tabEveFieldSpecified;
            }
            set {
                this.tabEveFieldSpecified = value;
                this.RaisePropertyChanged("tabEveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=85)]
        public System.Nullable<int> tipFat {
            get {
                return this.tipFatField;
            }
            set {
                this.tipFatField = value;
                this.RaisePropertyChanged("tipFat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipFatSpecified {
            get {
                return this.tipFatFieldSpecified;
            }
            set {
                this.tipFatFieldSpecified = value;
                this.RaisePropertyChanged("tipFatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=86)]
        public System.Nullable<int> tipIns {
            get {
                return this.tipInsField;
            }
            set {
                this.tipInsField = value;
                this.RaisePropertyChanged("tipIns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipInsSpecified {
            get {
                return this.tipInsFieldSpecified;
            }
            set {
                this.tipInsFieldSpecified = value;
                this.RaisePropertyChanged("tipInsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=87)]
        public string tipLgr {
            get {
                return this.tipLgrField;
            }
            set {
                this.tipLgrField = value;
                this.RaisePropertyChanged("tipLgr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=88)]
        public System.Nullable<int> tipUso {
            get {
                return this.tipUsoField;
            }
            set {
                this.tipUsoField = value;
                this.RaisePropertyChanged("tipUso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipUsoSpecified {
            get {
                return this.tipUsoFieldSpecified;
            }
            set {
                this.tipUsoFieldSpecified = value;
                this.RaisePropertyChanged("tipUsoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=89)]
        public System.Nullable<int> ultPes {
            get {
                return this.ultPesField;
            }
            set {
                this.ultPesField = value;
                this.RaisePropertyChanged("ultPes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultPesSpecified {
            get {
                return this.ultPesFieldSpecified;
            }
            set {
                this.ultPesFieldSpecified = value;
                this.RaisePropertyChanged("ultPesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=90)]
        public System.Nullable<int> viaCra {
            get {
                return this.viaCraField;
            }
            set {
                this.viaCraField = value;
                this.RaisePropertyChanged("viaCra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viaCraSpecified {
            get {
                return this.viaCraFieldSpecified;
            }
            set {
                this.viaCraFieldSpecified = value;
                this.RaisePropertyChanged("viaCraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=91)]
        public System.Nullable<int> viaPro {
            get {
                return this.viaProField;
            }
            set {
                this.viaProField = value;
                this.RaisePropertyChanged("viaPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viaProSpecified {
            get {
                return this.viaProFieldSpecified;
            }
            set {
                this.viaProFieldSpecified = value;
                this.RaisePropertyChanged("viaProSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class integracaoOutraEmpresaOutraEmpresaOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> codOemField;
        
        private bool codOemFieldSpecified;
        
        private string erroExecucaoField;
        
        private string retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codOem {
            get {
                return this.codOemField;
            }
            set {
                this.codOemField = value;
                this.RaisePropertyChanged("codOem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codOemSpecified {
            get {
                return this.codOemFieldSpecified;
            }
            set {
                this.codOemFieldSpecified = value;
                this.RaisePropertyChanged("codOemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface rubi_Syncbr_zopone_integracaoOutraEmpresaChannel : Zopone.AddOn.PO.SeniorOutraEmpresa.rubi_Syncbr_zopone_integracaoOutraEmpresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rubi_Syncbr_zopone_integracaoOutraEmpresaClient : System.ServiceModel.ClientBase<Zopone.AddOn.PO.SeniorOutraEmpresa.rubi_Syncbr_zopone_integracaoOutraEmpresa>, Zopone.AddOn.PO.SeniorOutraEmpresa.rubi_Syncbr_zopone_integracaoOutraEmpresa {
        
        public rubi_Syncbr_zopone_integracaoOutraEmpresaClient() {
        }
        
        public rubi_Syncbr_zopone_integracaoOutraEmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public rubi_Syncbr_zopone_integracaoOutraEmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_Syncbr_zopone_integracaoOutraEmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_Syncbr_zopone_integracaoOutraEmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaOut OutraEmpresa(string user, string password, int encryption, Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaIn parameters) {
            return base.Channel.OutraEmpresa(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaOut> OutraEmpresaAsync(string user, string password, int encryption, Zopone.AddOn.PO.SeniorOutraEmpresa.integracaoOutraEmpresaOutraEmpresaIn parameters) {
            return base.Channel.OutraEmpresaAsync(user, password, encryption, parameters);
        }
    }
}
